### ISSUE TITLE
The cods exist some little questions……

### ISSUE THREAD

**Issue by andashuai1997** [wang-chen/LGL#4]
The cods exist some little questions……
Could you please update the codes?

**Comment by wang-chen** [comment]
What questions? Can you point that out?

**Comment by andashuai1997** [comment]
In the file "/LGL/train.py",line 160 ,the first function "performance" includes five parameters，maybe you double the parameter"args.device"?
line 41,AttnAPPTrans and AttnAPPNPTrans are not mentioned.
At last,is the version of torch is below 1.10？I set torch=1.9.1.

**Comment by haleqiu** [comment]
@andashuai1997 Thank you for pointing this issue out. I make n update  #5 
We have test pytorch with `1.6` and `1.7`. Cloud you paste the issue you met with the pytorch?
